const Map=()=>{

return [
    [
        {'id':1,  'size': [1, 1], 'pos': [0, 0], 'type': 'sell' },
        {'id':2,  'size': [1, 1], 'pos': [1, 0], 'type': 'free' },
        {'id':3,  'size': [1, 1], 'pos': [2, 0], 'type': 'sell' },
        {'id':4,  'size': [1, 1], 'pos': [3, 0], 'type': 'free' },
        {'id':5,  'size': [1, 1], 'pos': [4, 0], 'type': 'free' },
        {'id':6,  'size': [1, 1], 'pos': [5, 0], 'type': 'free' },
        {'id':7,  'size': [1, 1], 'pos': [6, 0], 'type': 'sell' },
        {'id':8,  'size': [1, 1], 'pos': [7, 0], 'type': 'free' },
        {'id':9,  'size': [1, 1], 'pos': [8, 0], 'type': 'free' },
        {'id':10,  'size': [1, 1], 'pos': [9, 0], 'type': 'free' },
    ],
    [
        {'id':11,  'size': [1, 1], 'pos': [0, 1], 'type': 'free' },
        {'id':12,  'size': [1, 1], 'pos': [1, 1], 'type': 'free' },
        {'id':13,  'size': [1, 1], 'pos': [2, 1], 'type': 'free' },
        {'id':14,  'size': [1, 1], 'pos': [3, 1], 'type': 'free' },
        {'id':15,  'size': [1, 2], 'pos': [4, 1], 'type': 'sold' , 'image':'snoop.jpg' },
        {'id':16,  'size': [1, 1], 'pos': [5, 1], 'type': 'free' },
        {'id':17,  'size': [1, 1], 'pos': [6, 1], 'type': 'free' },
        {'id':18,  'size': [1, 1], 'pos': [7, 1], 'type': 'free' },
        {'id':19,  'size': [1, 1], 'pos': [8, 1], 'type': 'sell' },
        {'id':20,  'size': [1, 1], 'pos': [9, 1], 'type': 'free' },
    ],
    [
        {'id':21,  'size': [1, 1], 'pos': [0, 2], 'type': 'free' },
        {'id':22,  'size': [2, 2], 'pos': [1, 2], 'type': 'sold' , 'image':'atari.png' },
        // {'id':23,  'size': [1, 1], 'pos': [2, 2], 'type': 'free' },
        {'id':24,  'size': [1, 1], 'pos': [3, 2], 'type': 'free' },
        // {'id':25,  'size': [1, 1], 'pos': [4, 2], 'type': 'free' },
        {'id':26,  'size': [1, 1], 'pos': [5, 2], 'type': 'free' },
        {'id':27,  'size': [1, 1], 'pos': [6, 2], 'type': 'sold' , 'image':'sand.png' },
        {'id':28,  'size': [1, 1], 'pos': [7, 2], 'type': 'free' },
        {'id':29,  'size': [1, 1], 'pos': [8, 2], 'type': 'free' },
        {'id':30,  'size': [1, 1], 'pos': [9, 2], 'type': 'free' },
    ],
    [
        {'id':31,  'size': [1, 1], 'pos': [0, 3], 'type': 'free' },
        // {'id':32,  'size': [1, 1], 'pos': [1, 3], 'type': 'free' },
        // {'id':33,  'size': [1, 1], 'pos': [2, 3], 'type': 'free' },
        {'id':34,  'size': [1, 1], 'pos': [3, 3], 'type': 'free' },
        {'id':35,  'size': [1, 1], 'pos': [4, 3], 'type': 'free' },
        {'id':36,  'size': [1, 1], 'pos': [5, 3], 'type': 'free' },
        {'id':37,  'size': [1, 1], 'pos': [6, 3], 'type': 'free' },
        {'id':38,  'size': [1, 1], 'pos': [7, 3], 'type': 'free' },
        {'id':39,  'size': [1, 1], 'pos': [8, 3], 'type': 'free' },
        {'id':40,  'size': [1, 1], 'pos': [9, 3], 'type': 'free' },
    ],
    [
        {'id':41,  'size': [1, 1], 'pos': [0, 4], 'type': 'free' },
        {'id':42,  'size': [1, 1], 'pos': [1, 4], 'type': 'free' },
        {'id':43,  'size': [1, 1], 'pos': [2, 4], 'type': 'free' },
        {'id':44,  'size': [1, 1], 'pos': [3, 4], 'type': 'free' },
        {'id':45,  'size': [1, 1], 'pos': [4, 4], 'type': 'free' },
        {'id':46,  'size': [1, 1], 'pos': [5, 4], 'type': 'free' },
        {'id':47,  'size': [2, 2], 'pos': [6, 4], 'type': 'free' },
        // {'id':48,  'size': [1, 1], 'pos': [7, 4], 'type': 'free' },
        {'id':49,  'size': [1, 1], 'pos': [8, 4], 'type': 'free' },
        {'id':50,  'size': [1, 1], 'pos': [9, 4], 'type': 'free' },
    ],
    [
        {'id':51,  'size': [1, 1], 'pos': [0, 5], 'type': 'free' },
        {'id':52,  'size': [1, 1], 'pos': [1, 5], 'type': 'free' },
        {'id':53,  'size': [2, 2], 'pos': [2, 5], 'type': 'sell' },
        // {'id':54,  'size': [1, 1], 'pos': [3, 5], 'type': 'free' },
        {'id':55,  'size': [1, 1], 'pos': [4, 5], 'type': 'free' },
        {'id':56,  'size': [1, 1], 'pos': [5, 5], 'type': 'free' },
        // {'id':57,  'size': [1, 1], 'pos': [6, 5], 'type': 'free' },
        // {'id':58,  'size': [1, 1], 'pos': [7, 5], 'type': 'free' },
        {'id':59,  'size': [1, 1], 'pos': [8, 5], 'type': 'free' },
        {'id':60,  'size': [1, 1], 'pos': [9, 5], 'type': 'free' },
    ],
    [
        {'id':61,  'size': [1, 1], 'pos': [0, 6], 'type': 'free' },
        {'id':62,  'size': [1, 1], 'pos': [1, 6], 'type': 'free' },
        // {'id':63,  'size': [1, 1], 'pos': [2, 6], 'type': 'free' },
        // {'id':64,  'size': [1, 1], 'pos': [3, 6], 'type': 'free' },
        {'id':65,  'size': [1, 1], 'pos': [4, 6], 'type': 'free' },
        {'id':66,  'size': [1, 1], 'pos': [5, 6], 'type': 'free' },
        {'id':67,  'size': [1, 1], 'pos': [6, 6], 'type': 'free' },
        {'id':68,  'size': [1, 1], 'pos': [7, 6], 'type': 'free' },
        {'id':69,  'size': [1, 1], 'pos': [8, 6], 'type': 'free' },
        {'id':70,  'size': [1, 1], 'pos': [9, 6], 'type': 'free' },
    ],
    [
        {'id':71,  'size': [1, 1], 'pos': [0, 7], 'type': 'free' },
        {'id':72,  'size': [1, 1], 'pos': [1, 7], 'type': 'free' },
        {'id':73,  'size': [1, 1], 'pos': [2, 7], 'type': 'free' },
        {'id':74,  'size': [1, 1], 'pos': [3, 7], 'type': 'free' },
        {'id':75,  'size': [1, 1], 'pos': [4, 7], 'type': 'free' },
        {'id':76,  'size': [1, 1], 'pos': [5, 7], 'type': 'free' },
        {'id':77,  'size': [1, 1], 'pos': [6, 7], 'type': 'free' },
        {'id':78,  'size': [1, 1], 'pos': [7, 7], 'type': 'free' },
        {'id':79,  'size': [1, 1], 'pos': [8, 7], 'type': 'free' },
        {'id':80,  'size': [1, 1], 'pos': [9, 7], 'type': 'free' },
    ],
]

}

export default Map

